<?php

namespace Database\Seeders;

use App\Models\Partner;
use Illuminate\Database\Seeder;

class PartnerSeeder extends Seeder
{
    public function run(): void
    {
        $partners = [
            [
                'category' => 'producteur',
                'company_name' => 'Ferme Agricole Diomandé',
                'contact_name' => 'Sékou Diomandé',
                'country' => "Côte d'Ivoire",
                'city' => 'Man',
                'phone' => '+225 07 20 21 22 23',
                'whatsapp' => '+225 07 20 21 22 23',
                'email' => 'contact@fermediomande.ci',
                'website' => null,
                'sector' => 'Agriculture vivrière',
                'products_services' => 'Production de manioc, igname et banane plantain.',
                'capacities' => '50 tonnes / mois',
                'coverage_area' => 'Région du Tonkpi',
            ],
            [
                'category' => 'cooperative',
                'company_name' => 'Coopérative Cacaoyère de Soubré',
                'contact_name' => 'Marie-Claire Gnahoré',
                'country' => "Côte d'Ivoire",
                'city' => 'Soubré',
                'phone' => '+225 05 21 22 23 24',
                'whatsapp' => '+225 05 21 22 23 24',
                'email' => 'coop.soubre@cacaoci.org',
                'website' => 'www.coopcacaosoubre.ci',
                'sector' => 'Cacao certifié',
                'products_services' => 'Cacao fèves certifié Rainforest Alliance, fermentation et séchage.',
                'capacities' => '2 000 tonnes / campagne',
                'coverage_area' => 'Nawa et Gôh',
            ],
            [
                'category' => 'fabricant',
                'company_name' => 'Ivoire Plastiques Industries',
                'contact_name' => 'Bertrand Kacou',
                'country' => "Côte d'Ivoire",
                'city' => 'Abidjan',
                'phone' => '+225 01 22 23 24 25',
                'whatsapp' => '+225 01 22 23 24 25',
                'email' => 'contact@ivoireplastiques.ci',
                'website' => 'www.ivoireplastiques.ci',
                'sector' => 'Industrie plastique',
                'products_services' => 'Fabrication d\'emballages plastiques et bidons industriels.',
                'capacities' => '80 000 unités / mois',
                'coverage_area' => 'Côte d\'Ivoire, sous-région CEDEAO',
            ],
            [
                'category' => 'fournisseur',
                'company_name' => 'Sahel Import-Export SARL',
                'contact_name' => 'Aïcha Touré',
                'country' => 'Mali',
                'city' => 'Bamako',
                'phone' => '+223 76 23 24 25 26',
                'whatsapp' => '+223 76 23 24 25 26',
                'email' => 'a.toure@sahelimportexport.com',
                'website' => 'www.sahelimportexport.com',
                'sector' => 'Négoce international',
                'products_services' => 'Importation de matériaux de construction et quincaillerie.',
                'capacities' => 'Sur devis',
                'coverage_area' => 'Mali, Burkina Faso, Côte d\'Ivoire',
            ],
            [
                'category' => 'detenteur_stock',
                'company_name' => 'Anacarde du Nord SARL',
                'contact_name' => 'Yacouba Silué',
                'country' => "Côte d'Ivoire",
                'city' => 'Korhogo',
                'phone' => '+225 07 24 25 26 27',
                'whatsapp' => '+225 07 24 25 26 27',
                'email' => 'stocks@anacardedunord.ci',
                'website' => null,
                'sector' => 'Stockage anacarde',
                'products_services' => 'Stock disponible d\'anacarde brute, qualité export.',
                'capacities' => '1 200 tonnes en stock',
                'coverage_area' => 'Savanes',
            ],
            [
                'category' => 'proprietaire_actif',
                'company_name' => 'Koné Location Engins',
                'contact_name' => 'Lassina Koné',
                'country' => "Côte d'Ivoire",
                'city' => 'Bouaké',
                'phone' => '+225 05 25 26 27 28',
                'whatsapp' => '+225 05 25 26 27 28',
                'email' => 'lassina.kone@konelocation.ci',
                'website' => null,
                'sector' => 'Location d\'engins BTP',
                'products_services' => 'Location de pelles, chargeuses et camions-bennes.',
                'capacities' => '15 engins disponibles',
                'coverage_area' => 'Vallée du Bandama',
            ],
            [
                'category' => 'transporteur',
                'company_name' => 'Trans-Abidjan Logistique',
                'contact_name' => 'Hervé Digbeu',
                'country' => "Côte d'Ivoire",
                'city' => 'Abidjan',
                'phone' => '+225 01 26 27 28 29',
                'whatsapp' => '+225 01 26 27 28 29',
                'email' => 'operations@transabidjan.ci',
                'website' => 'www.transabidjan.ci',
                'sector' => 'Transport routier',
                'products_services' => 'Transport de marchandises et conteneurs, flotte de 40 camions.',
                'capacities' => '40 véhicules',
                'coverage_area' => 'Côte d\'Ivoire et corridor CEDEAO',
            ],
            [
                'category' => 'transitaire',
                'company_name' => 'Golfe de Guinée Transit',
                'contact_name' => 'Nadège Ehouman',
                'country' => "Côte d'Ivoire",
                'city' => 'Abidjan',
                'phone' => '+225 07 27 28 29 30',
                'whatsapp' => '+225 07 27 28 29 30',
                'email' => 'n.ehouman@ggtransit.ci',
                'website' => 'www.ggtransit.ci',
                'sector' => 'Transit et douane',
                'products_services' => 'Dédouanement, transit portuaire et gestion documentaire.',
                'capacities' => 'Port Autonome d\'Abidjan',
                'coverage_area' => 'Port d\'Abidjan, Port de San-Pédro',
            ],
            [
                'category' => 'entrepositaire',
                'company_name' => 'Warehouse Solutions CI',
                'contact_name' => 'Christian Angoua',
                'country' => "Côte d'Ivoire",
                'city' => 'Abidjan',
                'phone' => '+225 05 28 29 30 31',
                'whatsapp' => '+225 05 28 29 30 31',
                'email' => 'contact@warehousesolutions.ci',
                'website' => 'www.warehousesolutions.ci',
                'sector' => 'Entreposage',
                'products_services' => 'Entrepôts modernes, stockage sec et sous température dirigée.',
                'capacities' => '5 000 m² répartis sur 2 sites',
                'coverage_area' => 'Abidjan, Zone portuaire',
            ],
            [
                'category' => 'distributeur',
                'company_name' => 'Distri Ouest Afrique',
                'contact_name' => 'Ousmane Barry',
                'country' => 'Sénégal',
                'city' => 'Dakar',
                'phone' => '+221 77 29 30 31 32',
                'whatsapp' => '+221 77 29 30 31 32',
                'email' => 'o.barry@distriouestafrique.sn',
                'website' => 'www.distriouestafrique.sn',
                'sector' => 'Distribution B2B',
                'products_services' => 'Réseau de distribution de produits agroalimentaires et industriels.',
                'capacities' => 'Réseau de 120 points de vente',
                'coverage_area' => 'Sénégal, Mauritanie, Gambie',
            ],
        ];

        foreach ($partners as $item) {
            Partner::updateOrCreate(
                ['company_name' => $item['company_name']],
                [
                    'category' => $item['category'],
                    'contact_name' => $item['contact_name'],
                    'country' => $item['country'],
                    'city' => $item['city'],
                    'phone' => $item['phone'],
                    'whatsapp' => $item['whatsapp'],
                    'email' => $item['email'],
                    'website' => $item['website'],
                    'sector' => $item['sector'],
                    'products_services' => $item['products_services'],
                    'capacities' => $item['capacities'],
                    'coverage_area' => $item['coverage_area'],
                    'status' => 'valide',
                ]
            );
        }
    }
}
